### ISSUE TITLE
Plugin Implementation

### ISSUE THREAD

**Issue by aaryswastaken** [sleede/fab-manager#168]
Hello,

I am asking here even I know it's not the place for but how can we create any plugin or so. I didn't found any informations about it other than this plugin [example](https://github.com/LaCasemate/navinum-gamification/) but as FabManager is a big project, it's almost impossible to sort of retro-ingeneering files to know how to build properly an extension/plug-in. If I have to, I will but if there is another way, it would be easier. 
Maybe you want to not describe the entire procedure in order to keep things safe and I would understand but otherwise, where can I found some docs or infos about this type of project ?

Sincerly yours

**Comment by nflorentin** [comment]
Hi,

The plugin you mentioned is a good starting point. The main part of the plugin is the plugin.rb file which contains all the ruby code which hooks into the fab-manager application codebase reopening ruby classes. So yes, you will need to "retro-ingeneer" the app codebase to know his behaviour and detect which behaviour you want to modify or which behaviour you completely want to override.

You will obviously need a minimal knowledge of the frameworks Ruby on Rails to be able to develop a plugin for Fab-manager. Also, the complexity of the plugin will determine how difficult the task will be.

So, in order to get started with that, I would advise:
- read the README of the plugin which pretty much explains the role of every folder
- analyse the structure of the plugins (folders, file, how plugin.rb reopens ruby classes)
- analyse the part of the app you want to hook in (reservations, spaces, user creation, ...)

Do not hesitate to share your idea about the plugin you want to write as you can't do everything you want only reopening classes and adding assets, there are limitations and it could be more convenient to directly change the codebase (by forking the project or adding an optional feature, ...)

Good luck!
