### ISSUE TITLE
image size in the documentation tool

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#40]
hello, 

when i upload a big picture in a project, (in edit mode)
it upload a "medium" image in the preview of the page, (in view mode)
(and it generate a generic file name not usable for remembering which one has been upload, ...)
but when you clic on it (in view mode), in the project page, 
it only show this same medium image, in a new tab, 
https://fablab.lacasemate.fr/uploads/project_step_image/1010/medium_project_step_image.jpg
not the big one i upload, 
so it's not usable as a documentation picture 
(for exemple a schematics, or something else you need to see in big size)

**Comment by sylvainbx** [comment]
This feature was implemented in the commit referenced above.
It is available right now in the [dev](https://github.com/LaCasemate/fab-manager/tree/dev) branch or in the next stable release (2.4.0)

**Comment by Vincent14** [comment]
I can see pages that are so heavy to load that my browser show strange things, try yourself on this article https://fablab.lacasemate.fr/#!/projects/livre-de-cuisine

Is it possible to re-open this issue and think to create thumbnails with link to full size picture? It's so common on tools like WordPress that people will now expect this as a standard :)

**Comment by sylvainbx** [comment]
I have no special issue with my browsers (Chrome 53 / Firefox 49), everything looks fine. Witch browser/version are you using ? Can you post a screenshot ? Anyway, the images shown in the related article are external images (hosted on imgur), so this can't be related to the original issue. Consequently, I won't re-open it but feel free to open another issue if you think this is relevant.

**Comment by Vincent14** [comment]
Here is what I see:
![capture du 2016-10-25 20-07-50](https://cloud.githubusercontent.com/assets/1963080/19698274/ef9234f0-9aee-11e6-8c04-ea912e155cc7.png)
Perhaps it's because pictures are too heavy and not resized to the displayed resolution? With Firefox, try right click / page informations, and you'll see that in the "Dimensions" field:
![capture du 2016-10-25 20-13-11](https://cloud.githubusercontent.com/assets/1963080/19698447/986c1a82-9aef-11e6-8281-c770bcf285f3.png)

Firefox 49 on Ubuntu 16.04. Do you want I open a new isssue?
