### ISSUE TITLE
The upload limit for pictures is not suitable for common use

### ISSUE THREAD

**Issue by Vincent14** [sleede/fab-manager#52]
I don't know any modern photo camera able to take pictures less than 2MB, why is there this limitation? I can't imagine writing tutorial by resizing each picture before posting in a software able to do so much difficult other things! And the WYSIWYG toolbar offer a 4KB upload (kind of favicon?! For what?!).  

Please, free the power of the server by creating thumbnails!

**Comment by sylvainbx** [comment]
The 4kb upload is not really intended to be used. I know this sounds strange, but for historical reasons, we didn't wanted to remove this feature. The fact is that these images are stored as base64 text in database, this is not very efficient and must be avoided for large images.

We know this is not amazing at all but feel free to speak of your needs with [Pascal](https://forum.fab-manager.com/users/pascalmoutet/activity) on the [forum](https://forum.fab-manager.com/) as, I think, he's currently managing to redesign the things related to project's documentation.

**Comment by clemclemmm** [comment]
what kind of database admin store image in a database ???
since when a database is for storing image ???
you only store in database something that you can query on, if not, it's not in the database...

it's not because it's historical, that it's not a mistake, and that it has not to be changed...

what is that 4kb-base64-image for ? can't it be upload on the fileserver, as other files ?

it's not posible to say to our user "sorry, we give you a documentation plateform, but we don't allow you space on our server to upload your picture. you have to upload somewhere else, and put links in it". 
if we have our own server, of course we allow space for our user to upload pictures. 
if grenoble don't want, maybe it's there problem, but it's not what normal fablab will do. 
we need to upload picture, with a good size, for see details on the photo.

**Comment by pmoutet** [comment]
Hello,

@clemclemmm : nous avons bien pris en compte que c'était là un point sur lequel travailler. Côté Grenoble, la limite d'images n'a pas posé de problème jusqu'ici mais comme c'est un sujet à faire évoluer, nous  le ferons.

Ceci mis à part, je te trouve un peu virulent dans tes retours fait aux développeurs qui prennent le temps de dire les choses comme elles sont.

Nous avons conscience que, même si les choses fonctionnent plutôt bien, elles ne sont pas parfaites et il n'est pas nécessaire de t'offusquer : nos moyens sont limités et cela ne fera pas avancer les choses plus vite. 

Merci

**Comment by jarod022** [comment]
Pour compléter la réponse => https://forum.fab-manager.com/t/roadmap-les-nouvelles-fonctionnalites-a-venir-dici-fin-2016/69/13?u=sleede

**Comment by sylvainbx** [comment]
This feature was implemented in commit f1b749d5f23d07af4651abd086feeba56723090a.
Fab-manager now allows to configure an upload limit per instance, through the `MAX_IMAGE_SIZE` environment variable.
The stable [release 2.4.2](https://github.com/LaCasemate/fab-manager/releases/tag/v2.4.2) now contains this improvement.
