### ISSUE TITLE
setup script

### ISSUE THREAD

**Issue by clemclemmm** [sleede/fab-manager#57]
Hello, 
modern tools (in PHP) that want to be massive set up by user use a script for the setup process.
like owncloud / Wordpress / others.
first, the script will check the dependencies requiered, if not, ask to download and set up them, then will ask config option.
in this script, there would be the possibility to set the admin login and password (not using the default in the database), and other config option like set up the name of the lab, and other stuff.
at the end of the setup process, it will ask if you want to have a stripe account / access key (delivered by sleeve/lacasemate), and an open lab project, and by giving your email adress in the config part, will send a mail to both sleeve to generate the key, and the user to confirm that it's work in progress
and in the script, it wll be possible to run "update" that check the github if there is an update, download it, and upload it on the server. 

because we have all the setup procedure, and line of code, it whould be possible, now, no ?
is it possible in ROR to do that ?

**Comment by sylvainbx** [comment]
Hello Clement,
Yes, this kind of feature is (of course) technically possible, but we have no plans to do that in the near future. 
If you are skilled in ruby and angular, do not hesitate to contribute by coding your own module and we'll be happy to merge it into the project. Otherwise, the [fab-manager's days will take place at La Casemate on January 13 and 14, 2017](https://forum.fab-manager.com/t/save-the-date-premiere-rencontre-des-utilisateurs-de-fab-manager-a-la-casemate-les-13-14-janvier-2017/146). This will be a good place and time to convince other FabLabs that your feature request must be included in the common roadmap.

**Comment by clemclemmm** [comment]
hello, 
if fabmanager would be in PHP, 
i would already have done it. 

but i don't use ruby and angular.

it's a significant update for fab-manager to be more accessible to public.

**Comment by sylvainbx** [comment]
Tracking this new feature request is now done on [the website dedicated to the Fab-Manager's roadmap](https://roadmap.fab-manager.com/posts/21/open-format-for-project-exchange).
