### ISSUE TITLE
add default value of ENV

### ISSUE THREAD

**Issue by emj365** [sleede/fab-manager#72]
no ENV make App crash with the very weird error. 

As someone tries to run the system for the first time, specify a lot of ENVs to avoid system crash is not so good experience.

Some ENV can have the default value.

**Comment by emj365** [comment]
for example:

```
week_starting_day: <%= ENV["WEEK_STARTING_DAY"] ? ENV["WEEK_STARTING_DAY"] : 'monday' %>
```

**Comment by sylvainbx** [comment]
Default values for environment variables are already specified.
If you use docker, you can copy [env.example](https://github.com/LaCasemate/fab-manager/blob/master/docker/env.example) to `env`. Otherwise, in development you can copy [application.yml.default](https://github.com/LaCasemate/fab-manager/blob/master/config/application.yml.default) to `application.yml`.
